### ISSUE TITLE
The copyright notice should not say "All rights reserved"

### ISSUE THREAD

**Issue by aalex** [overture-stack/riff#20]
In the header of the files of the project it says:

"Copyright (c) 2018. The Ontario Institute for Cancer Research. All rights reserved."

Since the project is licensed under AGPL, some rights are reserved, but not all of them.

Hence, the phrase "All rights reserved." should be removed.

## Acceptance criterias
- Remove the phrase "All rights reserved." should be removed from all source files.

**Comment by rosibaj** [comment]
@aalex  We will have our legal consultant review this request.

**Comment by aalex** [comment]
That's a very good idea. I have written what I remember should be done, but I didn't verify it.

**Comment by rosibaj** [comment]
Was reviewed and the content will remain the same for now.
